"""
Convert scraped reviews into the website's testimonials data.

Run AFTER scrape_reviews.py:
    python generate_testimonials.py

What it does:
  1. Reads review_images/reviews.json
  2. Copies each review's first image to public/reviews/
  3. Writes src/data/testimonials.ts ready to import in the component
"""

import os
import json
import shutil

REVIEWS_JSON = "review_images/reviews.json"
IMAGES_SRC_DIR = "review_images"
PUBLIC_DEST_DIR = "public/reviews"
OUTPUT_TS = "src/data/testimonials.ts"

# Role label shown under reviewer name on the card
DEFAULT_ROLE = "Verified Google Review"


def main():
    if not os.path.exists(REVIEWS_JSON):
        print(f"ERROR: {REVIEWS_JSON} not found. Run scrape_reviews.py first.")
        return

    with open(REVIEWS_JSON, encoding="utf-8") as f:
        reviews = json.load(f)

    os.makedirs(PUBLIC_DEST_DIR, exist_ok=True)

    entries = []
    skipped = 0

    for review in reviews:
        img_files = review.get("image_files", [])
        if not img_files:
            skipped += 1
            continue

        # Use the first image for the card background
        src_path = os.path.join(IMAGES_SRC_DIR, img_files[0])
        if not os.path.exists(src_path):
            print(f"  WARNING: image not found, skipping — {src_path}")
            skipped += 1
            continue

        dest_filename = img_files[0]
        dest_path = os.path.join(PUBLIC_DEST_DIR, dest_filename)
        shutil.copy2(src_path, dest_path)

        entries.append({
            "image": f"/reviews/{dest_filename}",
            "stars": int(review.get("rating") or 5),
            "text": review.get("text", "").strip(),
            "name": review.get("reviewer", "Anonymous"),
            "role": DEFAULT_ROLE,
        })

    print(f"Processed {len(entries)} reviews ({skipped} skipped — no image or missing file)")

    # Build TypeScript file
    lines = [
        "// Auto-generated by generate_testimonials.py — do not edit manually",
        "// Re-run `python generate_testimonials.py` after a fresh scrape",
        "",
        "export interface Testimonial {",
        "  image: string;",
        "  stars: number;",
        "  text: string;",
        "  name: string;",
        "  role: string;",
        "}",
        "",
        "export const TESTIMONIALS: Testimonial[] = [",
    ]

    for e in entries:
        # Escape backticks/backslashes in text
        text = e["text"].replace("\\", "\\\\").replace("`", "\\`")
        name = e["name"].replace("\\", "\\\\").replace("`", "\\`")
        lines.append("  {")
        lines.append(f'    image: "{e["image"]}",')
        lines.append(f"    stars: {e['stars']},")
        lines.append(f'    text: `{text}`,')
        lines.append(f'    name: "{name}",')
        lines.append(f'    role: "{e["role"]}",')
        lines.append("  },")

    lines.append("];")
    lines.append("")

    os.makedirs(os.path.dirname(OUTPUT_TS), exist_ok=True)
    with open(OUTPUT_TS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written: {OUTPUT_TS}")
    print(f"Images copied to: {PUBLIC_DEST_DIR}/")
    print("\nNext step: the component already imports from this file.")


if __name__ == "__main__":
    main()
