// Auto-generated by generate_testimonials.py — do not edit manually
// Re-run `python generate_testimonials.py` after a fresh scrape

export interface Testimonial {
  image: string;
  stars: number;
  text: string;
  name: string;
  role: string;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    image: "/reviews/review_001_Matthew_Rowles_img1.jpg",
    stars: 5,
    text: `Best dog groomer I've been to in Sydney. I have an interesting little dog (see photos), so I like to make him look extra special. My requests are always greeted with excitement. Thank you for always making Elmo look sharp!`,
    name: "Matthew Rowles",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_002_Vicky_img1.jpg",
    stars: 5,
    text: `带猫猫去洗澡。店员态度很好`,
    name: "Vicky",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_003_Karen_img1.jpg",
    stars: 5,
    text: `Last weekend, I took my Schnauzer, OPPA to the baby pet studio.I was a little nervous at first because OPPA can be quite energetic and isn’t always a fan of getting groomed. But to my surprise, it turned out to be one of the most pleasant experiences we’ve had.

Before the grooming session began, they took the time to ask me about OPPA’s personality, grooming habits, and any special needs he might have. I really appreciated their patience and professionalism. They clearly cared about making the experience safe and enjoyable for both the pet and the owner.`,
    name: "Karen",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_004_Sherry_Liu_img1.jpg",
    stars: 5,
    text: `I would like to clarify the previous negative review. The cat in question is mine, and it was indeed frightened by the dog, which prompted the staff to intervene and stop their dog. My cat has been coming here for baths regularly, and the staff has always been very kind and attentive.`,
    name: "Sherry Liu",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_005_Zoe_img1.jpg",
    stars: 5,
    text: `Our two girls have been coming here since they were puppies, and we’ve always had great experiences with Baby Pet. We did switch to another place closer to home after the groomers changed, but recently friends told us the new team is fantastic—so we decided to come back. We’re so glad we did! The last two grooming sessions have been wonderful. Please don’t change the groomers again—our girls absolutely love it here, especially the one who usually gets anxious at other places.`,
    name: "Zoe",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_006_Elvis_Caus_img1.jpg",
    stars: 5,
    text: `Always responsive and very friendly. My Cavoodle is 8 years old and the other day I think they gave him the best haircut possible and attention to detail, very happy customer here. We will be back!`,
    name: "Elvis Caus",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_007_Kristy_H_img1.jpg",
    stars: 5,
    text: `Reasonable price and did a great job with my Cavoodle puppy. She came back happy - Thanks team!  Also it only took 2 hours which was a good time frame.`,
    name: "Kristy H",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_008_Xinyuan_Gao_img1.jpg",
    stars: 5,
    text: `我们一直在babypet洗澡 spa的产品可以根据毛孩子们的情况调整 味道好闻做完毛也光滑 对宠物们的温柔耐心让我很放心
另外店内有多种自制小零食、生骨肉，可爱的各种产品，日代韩代零食，很值得去店里逛逛`,
    name: "Xinyuan Gao",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_009_Rachel_Wang_img1.jpg",
    stars: 5,
    text: `Really good spa experience, they use good quality of grooming products and the groomers are all really patient to my boy, he quite enjoyed his bath time there~`,
    name: "Rachel Wang",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_010_YUAN_HU_img1.jpg",
    stars: 5,
    text: `超级棒的！长毛猫洗澡，前前后后洗了3遍！还给免费洗护用品升级了！猫咪在工作人员手里非常听话开心！家长还可以进入陪伴～我给满分！以后小朋友洗澡就去那里啦！`,
    name: "YUAN HU",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_011_Kathy_Zhao_(Kathy)_img1.jpg",
    stars: 5,
    text: `I recommend this place if you want to give a nice experience for your pets! I have been there many times and get a good service from the stuff if you treat them with respect, they definitely respond you friendly and make you satisfied about shopping and other services. The price I think it’s worthy for bath making my cat looks refreshing, enjoyable! My cat often do tidy includes wash, butt trim, nail trim and ear clean. Also, the treats sold in the store is my cat’s favorite! There are a number of different food with variety tastes I can choose, the price of some food even cheaper than many shops in Sydney. My cat loves this place more than I do！`,
    name: "Kathy Zhao (Kathy)",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_012_Jackie_Pan_img1.jpg",
    stars: 5,
    text: `Newly furnished place. The groomer Jane is really skilled and nice. Really enjoyed having my pet groomed here!`,
    name: "Jackie Pan",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_013_Taylor_Han_img1.jpg",
    stars: 5,
    text: `My little long-haired dachshund had twice spa here already, I can see my boy is very satisfied with the service :)
The staff is very professional that is the most important part to be a owner of a pet store, and also they are very friendly for answering your questions.
And they took very nice photo for my boy!!!
Highly recommend!!!`,
    name: "Taylor Han",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_014_Elaine_Yu_img1.jpg",
    stars: 5,
    text: `I took two dogs there for wash and tidy. Baby pet has been very helpful and professional in pet bathing and grooming. Their coating after the bath was shiny, soft and smooth. One of my dog used to be stressful when I took her to other places for bathing. But she enjoyed it at Baby Pet this time. The groomer was very responsible and patient. Also reasonable prices around the Sydney city area.`,
    name: "Elaine Yu",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_015_Kongsak_Boonkerd_img1.jpg",
    stars: 5,
    text: `My dog have a very good experience at this grooming shop. J is a very good groomer. She make my dog soooooo cute. The toy and Christmas discount are nice.`,
    name: "Kongsak Boonkerd",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_016_rao_ya_nan_img1.jpg",
    stars: 5,
    text: `great place for grooming！`,
    name: "rao ya nan",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_017_Jingcheng_Hong_img1.jpg",
    stars: 5,
    text: `洗的超级棒 推荐spa！！！！`,
    name: "Jingcheng Hong",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_018_Panda_gao_img1.jpg",
    stars: 5,
    text: `My Bucky had a spa, shampoo and tidy up in this store. It was a wonderful experience and will definitely recommend to all my friends with pets.
Staffs are friendly,  shop is clean, Bucky loves this place.
One of the best pet shop in greensquare area.`,
    name: "Panda gao",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_019_Jun_Wu_img1.jpg",
    stars: 5,
    text: ``,
    name: "Jun Wu",
    role: "Verified Google Review",
  },
  {
    image: "/reviews/review_020_Irina_img1.jpg",
    stars: 5,
    text: `Lovely pet shop, my dog loved her bath, staff was friendly and professional, will definitely come back again!`,
    name: "Irina",
    role: "Verified Google Review",
  },
];
